//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capa_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factore()
        {
            this.Pestels = new HashSet<Pestel>();
        }
    
        public int Id_factor { get; set; }
        public int Id_idea { get; set; }
        public string factor { get; set; }
        public bool id_tipo_factor { get; set; }
    
        public virtual Idea Idea { get; set; }
        public virtual Tipo_Factor Tipo_Factor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pestel> Pestels { get; set; }
    }
}
