//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capa_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factore
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Factore()
        {
            this.Pestels = new HashSet<Pestel>();
        }
    
        public int Id_factor { get; set; }
        public int Id_idea { get; set; }
        public string factor { get; set; }
        public bool id_tipo_factor { get; set; }
    
        public virtual Idea Idea { get; set; }
        public virtual Tipo_Factor Tipo_Factor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pestel> Pestels { get; set; }
    }
}
