//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capa_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ideas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ideas()
        {
            this.Factores = new HashSet<Factores>();
        }
    
        public int Id_idea { get; set; }
        public int Id_caracteristica { get; set; }
        public string idea { get; set; }
        public int Id_hoja_resultados { get; set; }
    
        public virtual Caracteristicas Caracteristicas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Factores> Factores { get; set; }
        public virtual Hoja_Resultados Hoja_Resultados { get; set; }
    }
}
