//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capa_datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tiusr7pl_proyecto_relampagoEntities : DbContext
    {
        public tiusr7pl_proyecto_relampagoEntities()
            : base("name=tiusr7pl_proyecto_relampagoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Afecta> Afecta { get; set; }
        public virtual DbSet<Caracteristicas> Caracteristicas { get; set; }
        public virtual DbSet<Clasificacion> Clasificacion { get; set; }
        public virtual DbSet<Factores> Factores { get; set; }
        public virtual DbSet<Hoja_Resultados> Hoja_Resultados { get; set; }
        public virtual DbSet<Ideas> Ideas { get; set; }
        public virtual DbSet<Pestel> Pestel { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    }
}
