//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capa_datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tiusr7pl_proyecto_relampagoEntities : DbContext
    {
        public tiusr7pl_proyecto_relampagoEntities()
            : base("name=tiusr7pl_proyecto_relampagoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Caracteristica> Caracteristicas { get; set; }
        public virtual DbSet<Factore> Factores { get; set; }
        public virtual DbSet<Hoja_Resultados> Hoja_Resultados { get; set; }
        public virtual DbSet<Idea> Ideas { get; set; }
        public virtual DbSet<Pestel> Pestels { get; set; }
        public virtual DbSet<Tipo_Factor> Tipo_Factor { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
