//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capa_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pestel
    {
        public int Id_pestel { get; set; }
        public int Id_factor { get; set; }
        public bool tipoFactor { get; set; }
        public int clasificacion_factor { get; set; }
        public int Politico { get; set; }
        public int Economico { get; set; }
        public int Social { get; set; }
        public int Tecnologico { get; set; }
        public int Ecologico { get; set; }
        public int Legal { get; set; }
        public string Comentario { get; set; }
        public int Id_hoja_resultados { get; set; }
    
        public virtual Afecta Afecta { get; set; }
        public virtual Afecta Afecta1 { get; set; }
        public virtual Afecta Afecta2 { get; set; }
        public virtual Afecta Afecta3 { get; set; }
        public virtual Afecta Afecta4 { get; set; }
        public virtual Afecta Afecta5 { get; set; }
        public virtual Clasificacion Clasificacion { get; set; }
        public virtual Hoja_Resultados Hoja_Resultados { get; set; }
    }
}
