//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace capa_datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pestel
    {
        public int Id_factor { get; set; }
        public int Id_pestel { get; set; }
        public string clasificacion_factor { get; set; }
        public Nullable<bool> Economico { get; set; }
        public Nullable<bool> Social { get; set; }
        public Nullable<bool> Tecnologico { get; set; }
        public Nullable<bool> Ecologico { get; set; }
        public Nullable<bool> Legal { get; set; }
        public string Comentario { get; set; }
    
        public virtual Factore Factore { get; set; }
    }
}
