//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tiusr7pl_proyecto_relampagoEntities : DbContext
    {
        public tiusr7pl_proyecto_relampagoEntities()
            : base("name=tiusr7pl_proyecto_relampagoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Caracteristica> Caracteristicas { get; set; }
        public virtual DbSet<Factore> Factores { get; set; }
        public virtual DbSet<Hoja_Resultados> Hoja_Resultados { get; set; }
        public virtual DbSet<Idea> Ideas { get; set; }
        public virtual DbSet<Pestel> Pestels { get; set; }
        public virtual DbSet<Tipo_Factor> Tipo_Factor { get; set; }
        public virtual DbSet<Usuario> Usuarios { get; set; }
    }
}
