//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pestel
    {
        public int Id_factor { get; set; }
        public int Id_pestel { get; set; }
        public string clasificacion_factor { get; set; }
        public Nullable<bool> Economico { get; set; }
        public Nullable<bool> Social { get; set; }
        public Nullable<bool> Tecnologico { get; set; }
        public Nullable<bool> Ecologico { get; set; }
        public Nullable<bool> Legal { get; set; }
        public string Comentario { get; set; }
    
        public virtual Factore Factore { get; set; }
    }
}
